/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 10/08/2018 12:17:17
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            25000000
#define MX_SYSCLKFreq_VALUE                     75000000
#define MX_HCLKFreq_Value                       75000000
#define MX_FCLKCortexFreq_Value                 75000000
#define MX_CortexFreq_Value                     75000000
#define MX_AHBFreq_Value                        75000000
#define MX_APB1Freq_Value                       75000000
#define MX_APB2Freq_Value                       75000000
#define MX_APB1TimFreq_Value                    75000000
#define MX_APB2TimFreq_Value                    75000000
#define MX_PWRFreq_Value                        75000000
#define MX_RTCFreq_Value                        781250
#define MX_USBFreq_Value                        50000000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    75000000

/*-------------------------------- ADC1       --------------------------------*/

#define MX_ADC1                                 1

/* GPIO Configuration */

/* Pin PA6 */
#define MX_ADCx_IN11_Pin                        PA6
#define MX_ADCx_IN11_GPIOx                      GPIOA
#define MX_ADCx_IN11_GPIO_PuPd                  GPIO_NOPULL
#define MX_ADCx_IN11_GPIO_Pin                   GPIO_PIN_6
#define MX_ADCx_IN11_GPIO_Mode                  GPIO_MODE_ANALOG_ADC_CONTROL

/* Pin PA3 */
#define MX_ADCx_IN8_Pin                         PA3
#define MX_ADCx_IN8_GPIOx                       GPIOA
#define MX_ADCx_IN8_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADCx_IN8_GPIO_Pin                    GPIO_PIN_3
#define MX_ADCx_IN8_GPIO_Mode                   GPIO_MODE_ANALOG_ADC_CONTROL

/* NVIC Configuration */

/* NVIC ADC1_IRQn */
#define MX_ADC1_IRQn_interruptPremptionPriority 1
#define MX_ADC1_IRQn_PriorityGroup              NVIC_PRIORITYGROUP_4
#define MX_ADC1_IRQn_Subriority                 0

/*-------------------------------- DMA        --------------------------------*/

#define MX_DMA                                  1

/* DMA Configuration */

/* DMA DMA1_Channel1 */
#define MX_DMA1_Channel1_DMA_DMA_Handle         
#define MX_DMA1_Channel1_DMA_Instance           DMA1_Channel1
#define MX_DMA1_Channel1_DMA_NoTestForDmaSupport false
#define MX_DMA1_Channel1_DMA_Priority           DMA_PRIORITY_HIGH
#define MX_DMA1_Channel1_DMA_PeriphDataAlignment DMA_PDATAALIGN_WORD
#define MX_DMA1_Channel1_DMA_MemDataAlignment   DMA_MDATAALIGN_WORD
#define MX_DMA1_Channel1_DMA_Mode               DMA_NORMAL
#define MX_DMA1_Channel1_DMA_Request            DMA_REQUEST_0
#define MX_DMA1_Channel1_DMA_Direction          DMA_MEMORY_TO_MEMORY
#define MX_DMA1_Channel1_DMA_PeriphInc          DMA_PINC_ENABLE
#define MX_DMA1_Channel1_DMA_MemInc             DMA_MINC_ENABLE
#define MX_DMA1_Channel1_DMA_IpInstance         

/* DMA DMA1_Channel2 */
#define MX_DMA1_Channel2_DMA_DMA_Handle         
#define MX_DMA1_Channel2_DMA_Instance           DMA1_Channel2
#define MX_DMA1_Channel2_DMA_NoTestForDmaSupport false
#define MX_DMA1_Channel2_DMA_Priority           DMA_PRIORITY_MEDIUM
#define MX_DMA1_Channel2_DMA_PeriphDataAlignment DMA_PDATAALIGN_WORD
#define MX_DMA1_Channel2_DMA_MemDataAlignment   DMA_MDATAALIGN_WORD
#define MX_DMA1_Channel2_DMA_Mode               DMA_NORMAL
#define MX_DMA1_Channel2_DMA_Request            DMA_REQUEST_0
#define MX_DMA1_Channel2_DMA_Direction          DMA_MEMORY_TO_MEMORY
#define MX_DMA1_Channel2_DMA_PeriphInc          DMA_PINC_ENABLE
#define MX_DMA1_Channel2_DMA_MemInc             DMA_MINC_ENABLE
#define MX_DMA1_Channel2_DMA_IpInstance         

/*-------------------------------- IWDG       --------------------------------*/

#define MX_IWDG                                 1

/* GPIO Configuration */

/*-------------------------------- RTC        --------------------------------*/

#define MX_RTC                                  1

/* GPIO Configuration */

/* NVIC Configuration */

/* NVIC RTC_Alarm_IRQn */
#define MX_RTC_Alarm_IRQn_interruptPremptionPriority 7
#define MX_RTC_Alarm_IRQn_PriorityGroup         NVIC_PRIORITYGROUP_4
#define MX_RTC_Alarm_IRQn_Subriority            0

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 (JTMS-SWDIO) */
#define MX_SYS_JTMS-SWDIO_Pin                   PA13_(JTMS_SWDIO)
#define MX_SWDIO                                SYS_JTMS-SWDIO

/* Pin PA14 (JTCK-SWCLK) */
#define MX_SYS_JTCK-SWCLK_Pin                   PA14_(JTCK_SWCLK)
#define MX_SWCLK                                SYS_JTCK-SWCLK

/*-------------------------------- TIM1       --------------------------------*/

#define MX_TIM1                                 1

/* GPIO Configuration */

/* Pin PA9 */
#define MX_S_TIM1_CH2_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM1_CH2_GPIO_Speed                GPIO_SPEED_FREQ_VERY_HIGH
#define MX_S_TIM1_CH2_Pin                       PA9
#define MX_S_TIM1_CH2_GPIOx                     GPIOA
#define MX_S_TIM1_CH2_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM1_CH2_GPIO_Pin                  GPIO_PIN_9
#define MX_S_TIM1_CH2_GPIO_AF                   GPIO_AF1_TIM1

/* Pin PB0 */
#define MX_TIM1_CH2N_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_TIM1_CH2N_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_TIM1_CH2N_Pin                        PB0
#define MX_TIM1_CH2N_GPIOx                      GPIOB
#define MX_TIM1_CH2N_GPIO_PuPd                  GPIO_NOPULL
#define MX_TIM1_CH2N_GPIO_Pin                   GPIO_PIN_0
#define MX_TIM1_CH2N_GPIO_AF                    GPIO_AF1_TIM1

/* NVIC Configuration */

/* NVIC TIM1_BRK_TIM15_IRQn */
#define MX_TIM1_BRK_TIM15_IRQn_interruptPremptionPriority 0
#define MX_TIM1_BRK_TIM15_IRQn_PriorityGroup    NVIC_PRIORITYGROUP_4
#define MX_TIM1_BRK_TIM15_IRQn_Subriority       0

/*-------------------------------- TIM6       --------------------------------*/

#define MX_TIM6                                 1

/* GPIO Configuration */

/* NVIC Configuration */

/* NVIC TIM6_DAC_IRQn */
#define MX_TIM6_DAC_IRQn_interruptPremptionPriority 6
#define MX_TIM6_DAC_IRQn_PriorityGroup          NVIC_PRIORITYGROUP_4
#define MX_TIM6_DAC_IRQn_Subriority             0

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PA2 */
#define MX_PA2_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA2_Pin                              PA2
#define MX_PA2_GPIOx                            GPIOA
#define MX_PA2_PinState                         GPIO_PIN_SET
#define MX_PA2_GPIO_PuPd                        GPIO_NOPULL
#define MX_U_gen                                PA2
#define MX_PA2_GPIO_Pin                         GPIO_PIN_2
#define MX_PA2_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA1 */
#define MX_PA1_Pin                              PA1
#define MX_PA1_GPIOx                            GPIOA
#define MX_PA1_GPIO_PuPd                        GPIO_NOPULL
#define MX_PA1_GPIO_Pin                         GPIO_PIN_1
#define MX_PA1_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PB5 */
#define MX_PB5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB5_Pin                              PB5
#define MX_PB5_GPIOx                            GPIOB
#define MX_PB5_PinState                         GPIO_PIN_RESET
#define MX_PB5_GPIO_PuPd                        GPIO_NOPULL
#define MX_AnalogStage                          PB5
#define MX_PB5_GPIO_Pin                         GPIO_PIN_5
#define MX_PB5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PA5 */
#define MX_PA5_Pin                              PA5
#define MX_PA5_GPIOx                            GPIOA
#define MX_PA5_GPIO_PuPd                        GPIO_NOPULL
#define MX_PA5_GPIO_Pin                         GPIO_PIN_5
#define MX_PA5_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PA10 */
#define MX_PA10_Pin                             PA10
#define MX_PA10_GPIOx                           GPIOA
#define MX_PA10_GPIO_PuPd                       GPIO_PULLDOWN
#define MX_USB_V                                PA10
#define MX_PA10_GPIO_Pin                        GPIO_PIN_10
#define MX_PA10_GPIO_Mode                       GPIO_MODE_INPUT

/* Pin PA15 (JTDI) */
#define MX_PA15_(JTDI)_GPIO_Speed               GPIO_SPEED_FREQ_VERY_HIGH
#define MX_PA15_(JTDI)_Pin                      PA15_(JTDI)
#define MX_PA15_(JTDI)_GPIOx                    GPIOA
#define MX_PA15_(JTDI)_PinState                 GPIO_PIN_RESET
#define MX_PA15_(JTDI)_GPIO_PuPd                GPIO_NOPULL
#define MX_U_GEN                                PA15_(JTDI)
#define MX_PA15_(JTDI)_GPIO_Pin                 GPIO_PIN_15
#define MX_PA15_(JTDI)_GPIO_ModeDefaultOutputPP GPIO_MODE_OUTPUT_PP

/* Pin PA7 */
#define MX_PA7_Pin                              PA7
#define MX_PA7_GPIOx                            GPIOA
#define MX_PA7_GPIO_PuPd                        GPIO_PULLUP
#define MX_LED_But                              PA7
#define MX_PA7_GPIO_Pin                         GPIO_PIN_7
#define MX_PA7_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_FALLING

/* Pin PB3 (JTDO-TRACESWO) */
#define MX_PB3_(JTDO_TRACESWO)_GPIO_Speed       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_PB3_(JTDO_TRACESWO)_Pin              PB3_(JTDO_TRACESWO)
#define MX_PB3_(JTDO_TRACESWO)_GPIOx            GPIOB
#define MX_PB3_(JTDO_TRACESWO)_PinState         GPIO_PIN_RESET
#define MX_PB3_(JTDO_TRACESWO)_GPIO_PuPd        GPIO_NOPULL
#define MX_LD3_[Green]                          PB3_(JTDO_TRACESWO)
#define MX_PB3_(JTDO_TRACESWO)_GPIO_Pin         GPIO_PIN_3
#define MX_PB3_(JTDO_TRACESWO)_GPIO_ModeDefaultOutputPP GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

