SET PATH=C:\Keil_v5\ARM\ARMCC\Bin;C:\Keil_v5\ARM\ARMCLANG\Bin;C:\Program Files (x86)\STMicroelectronics\STM32Cube\STM32CubeMX\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\MATLAB\R2015b\runtime\win64;C:\Program Files\MATLAB\R2015b\bin;C:\Program Files\MATLAB\R2015b\polyspace\bin;C:\Qt\Qt5.7.0\Tools\mingw530_32\bin;C:\Program Files (x86)\Kaspersky Lab\Kaspersky Endpoint Security 10 for Windows SP1\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Atmel\Flip 3.4.7\bin;C:\Program Files (x86)\Java\jre1.8.0_101\bin
SET CPU_TYPE=STM32L432KCUx
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=PAM
SET CPU_CLOCK=0x04C4B400
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\pam\stm32l4xx_hal_cortex.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\pam\stm32l4xx_hal_flash_ramfunc.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via ".\pam\stm32l4xx_hal_rcc.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmLink" --Via ".\PAM\PAM.lnp"
